### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by stump9** [mentionbb/mention-pacman#1]
Can you add in the readme how someone can install this from a noob perspective. Kindly.

**Comment by par274** [comment]
Simply move files.

I'm busy writing documentation.

**Comment by stump9** [comment]
From where to where?  do you need help in documentation writing?

**Comment by stump9** [comment]
Fixed

**Comment by stump9** [comment]
![Screenshot 2023-02-26 at 00 24 10](https://user-images.githubusercontent.com/126314444/221380268-f7ff8ce4-a1d7-4a0e-b947-944ed0bba0b9.png)
got this error

**Comment by par274** [comment]
Ok i see the problem.

You simply need to move the app file in public/vendor/pacman/game/build to the previous game folder.

Or you can download the updated files again.

https://github.com/mentionbb/mention-pacman/archive/refs/tags/mentionbb-pacman-addon-2.zip

**Comment by stump9** [comment]
Fixed with the latest release
